### ISSUE TITLE
Instructions to add a user to WKS are not incorrect.

### ISSUE THREAD

**Issue by marycparmelee** [IBM-Bluemix-Docs/knowledge-studio#2]
FYI, I want to convert a single user account to multiple user account. The instructions to add a user reference a "more actions" button that doesn't exist and upgrade my account link send me to open a new account instead of upgrading my existing account.

**Comment by jdicarl** [comment]
Thanks for creating an issue. Do you mean Step 2 of this page? https://console.bluemix.net/docs/services/knowledge-studio/team.html#procedure

If not, can you post the URL? Thank you!

**Comment by jdicarl** [comment]
@marycparmelee 
You can't see the **More actions** button unless you have a plan that includes more than one user. The task is for adding users (which doesn't work with free or single-user plans), and that should've been more clear.

So before you use this task, you would need to upgrade your plan:

1. Click the **Manage** button on the Watson Knowledge Studio tile.

2. In the **Upgrade or change plan** section, click **Purchase now**, which will allow you to change from a free plan to the standard plan (or add users if you already have the standard plan for one user).
![image](https://user-images.githubusercontent.com/13224537/31143441-625989d8-a84b-11e7-9392-68569b39a189.png)

The documentation isn't clear because in the prerequisites for this task it says that you can use a free plan, which I will change:
>From IBM Marketplace External link icon, sign up for a free plan or purchase a subscription to use IBM Watson™ Knowledge Studio.

**Comment by marycparmelee** [comment]
Hi,
This turned out to be an issue with my account that prevented me from being able to upgrade my plan. It was resolved over a month ago.
Thanks anyway,Mary Parmelee 

    On Tuesday, October 3, 2017 3:12 PM, jdicarl <notifications@github.com> wrote:
 

 @marycparmelee
You can't see the More actions button unless you have a plan that includes more than one user. The task is for adding users (which doesn't work with free or single-user plans), and that should've been more clear.So before you use this task, you would need to upgrade your plan:   
   - Click the Manage button on the Watson Knowledge Studio tile.
   - In the Upgrade or change plan section, click Purchase now, which will allow you to change from a free plan to the standard plan (or add users if you already have the standard plan for one user).   

The documentation isn't clear because in the prerequisites for this task it says that you can use a free plan, which I will change:
From IBM Marketplace External link icon, sign up for a free plan or purchase a subscription to use IBM Watson™ Knowledge Studio.

**Comment by jdicarl** [comment]
Doc is updated https://console.bluemix.net/docs/services/knowledge-studio/team.html
